from TaxEncoding1 import y as chrs
from TaxEncoding1 import hoho as ords

a,b='from pkg import *\ndef helloworld():\n\tprint(\'me : hello world\')\ndef main():\n\thelloworld()\n\tprint(\'world :\',dirs())\nif __name__=="__main__":main()','def helloworld():\n\tprint(\'me : hello world\')\nmain:\n\thelloworld()\n\tprint(\'world :\',dirs())'
print('\nsourse of a',':')
input()
print(a)
input()
print('\t\tVS')
input()
print('\nsourse of b',':')
input()
print(b)
input()
print("\n\n(NOTE : actually same code, but who's code is better? A?, B?)\n\n")
input()
print('so,... first, how about with are havy?')
input()
print('\ttext')
input()
print('\t\twords that a:'+str(len(a)),'\t\twords that b:'+str(len(b)),sep='\n\t\t\t\tvs\n')
print('\n\n\t\twow, What do you think about it? :)')
input()
print('\t\ta has more',len(a)-len(b),'words ;)')
print('\t\tSpace saving ratio',(1-len(b)/len(a))*100,'%')
input()
print('\tbinarry')
input()
a2=chrs(a)
b2=chrs(b)
print('\t\twords that a:'+str(len(a2)),'\t\twords that b:'+str(len(b2)),sep='\n\t\t\t\tvs\n')
print('\n\n\t\twow, What do you think about it? :)')
input()
print('\t\ta has more',len(a2)-len(b2),'bits ;)')
print('\t\tSpace saving ratio',(1-len(b2)/len(a2))*100,'%')
input()
